version: '3.3'
services:
  web:
    image: tubes-1:latest
    build:
      context: ./
      dockerfile: Dockerfile      
    ports:
      - 8080:80
    volumes:
      - ./:/var/www/html
      - "./app/.htaccess:/var/www/html/app/.htaccess"
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: song_database
        MYSQL_USER: user
        MYSQL_PASSWORD: user
    ports:
        - "9906:3306"
    volumes:
      - ./dump/dump.sql:/docker-entrypoint-initdb.d/dump.sql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8008:80'
    restart: always
    environment:
        PMA_HOST: db
        UPLOAD_LIMIT: 1G
    depends_on:
        - db
